[project]
name = "ruler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "nltk>=3.9.1",
    "pandas>=2.3.2",
    "tqdm>=4.67.1",
    "wikiextractor>=3.0.6",
]
